<?php
   define("HOSPITALCOURSEID","id");
   define("HOSNAME","Hospital name");
   define("HOSFILE","Hospital file no.");
   define("ADMISSIONADTE","Admission date");
   define("SURGEONNAME","Surgeon Name");
   define("PREWEIGHTREDUC","Preoperative weight reduction");
   define("PREWEIGHTREDUCMUCH","How much");
   define("OPERDATE","Operation date");
   define("OPERSTARTTIME","Operation Start Time");
   define("OPERENDTIME","Operation End Time");
   define("OPERTYPE","Operation type");
   define("HOSMETHOD","Method");
   define("CONTOLAP","Conversion to laparotomy");
   define("CONTOLAPPEASON","Reason");
   define("LEALAGEBLUE","Leakage test with Methylene blue");
   define("LEALAGEBLUEC"," ");
   define("SLEEVEGAS","Sleeve Gastrectomy");
   define("REDO","Redo Sleeve");
   define("REDOBYPASS","Redo Bypass");
   define("SADIBYPASS","Sadi Bypass");
   define("SASIBYPASS","Sasi Bypass");
   define("MINIBYPASS","Mini Bypass");
   define("REGABY","Reux-en-Y Gastric Bypass");
   define("GABAND","Gastric Band");
   define("DUSWITCH","Duodenal Switch");
   define("VERBANDGA","Vertical band gastroplasty");
   define("JEJBY","Jejunoileal bypass");
   define("CHOLECYST","Cholecystectomy");
   define("REPAIRHERNIA","Repair of hernia");
   define("HOSOTHER","Other");
   define("OTHERG"," ");
   define("TROCAR","Trocar injuries");
   define("SPLENIC","Splenic injury");
   define("VASCULAR","Vascular injury");
   define("BOWEL","Bowel injury");
   define("ISCHEMIA","Bowel ischemia");
   define("MISCONSTRUCTION","Misconstruction");
   define("MELEAKAGE","Methylene blue leakage");
   define("OTHERKIND","Other kind");
   define("OTHERKINDD"," ");
   define("REACOMP","Reason for complication");
   define("WHATWASD","What was done?");
   define("UPGISEFI","Upper GI Series findings");
   define("POSTOPESR","ESR");
   define("POSTOPCRP","CRP");
   define("POSTOPHB","HB");
   define("POSTOPHCT","HCT");
   define("EARCOMPAN","Anastomotic leak");
   define("EARCOMPBL","Bleeding");
   define("EARCOMPST","Stenosis");
   define("EARCOMPOB","Obstruction");
   define("EARCOMPIN","Infection");
   define("EARCOMPDV","DVT");
   define("EARCOMPDVEMB","Embolization");
   define("EARCOMPCARD","Cardiovascular complications");
   define("EARCOMPCARDACS","ACS");
   define("EARCOMPCARDCHF","CHF");
   define("EARCOMPCARDARR","Arrhythmia");
   define("EARCOMPRES","Respiratory failure");
   define("EARCOMPOTHER","Other");
   define("EARCOMPOTHERR","Other");
   define("EARCOMPWWTPSASOFC","What was the patient�s sing and symptoms of the complication?");
   define("EARCOMPWWDONE","What was done?");
   define("NUTEDU","Nutritional education");
   define("NUTEDUVER","version");
   define("MEDIINHOS","Medication in hospital course");
   define("MEDCEFTRIAXONE","Ceftriaxone");
   define("MEDMETRONIDAZOLE","Metronidazole");
   define("MEDPETHIDINE","Pethidine");
   define("MEDDICLOPHENAC","Diclophenac");
   define("MEDRANITIDINE","Ranitidine");
   define("MEDGLUCOSAN","Glucosan");
   define("DISCHARGEDATE","Discharge date");
   define("PREMED","Prescripted Medications");
   define("PREMEDCEPHALEXIN", "Cefalexin Syrup(one tablespoon every 6 hours)");
   define("PREMEDRANITIDINE","Ranitidine Syrup(two tablespoons every 8 hours)");
   define("PREMEDDICLOFENAC", "Diclofenac Suppository(one when pain)");
   define("PREMEDCELEXAN40MG","Celexan 40MG Ampoule(1 a day till 5 days)");
   define("TRANSFERTO","Transfer To");
   define("COM_HOSPITALCOURSE"," ");
   define("HOSPITALCOURSE_REQUIRE_FIELDS","");
   define("MSG_HOSPITALCOURSE_SAVE","Saving Successfully");
   define("MSG_HOSPITALCOURSE_DELETE","Delete Successfully");
?>

