<?php
   define("FAMILY_AND_SOCIAL_HXID","id");
   define("OBESITY","Obesity");
   define("OBESITYWHO","who");
   define("PROSTATECANCER","Prostate cancer");
   define("PROSTATECANCERWHO","who");
   define("FDM","DM");
   define("DMWHO","who");
   define("OTHERMALIGNANCY","Other malignancy");
   define("OTHERMALIGNANCYWHO","who");
   define("FHTN","HTN");
   define("HTNWHO","who");
   define("RENTALSTONE","Renal stone");
   define("RENTALSTONEWHO","who");
   define("HYPOTHYROIDISM","Hypothyroidism");
   define("HYPOTHYROIDISMWHO","who");
   define("FGALLSTONE","Gall stone");
   define("GALLSTONEWHO","who");
   define("BREASTCANCER","Breast cancer");
   define("BREASTCANCERWHO","who");
   define("FGOUT","Gout");
   define("GOUTWHO","who");
   define("COLONCANCER","Colon cancer");
   define("COLONCANCERWHO","who");
   define("MULTIPLEGESTATION","Multiple gestation");
   define("MULTIPLEGESTATIONWHO","who");
   define("ENDOMETRIALCANCER","Endometrial cancer");
   define("ENDOMETRIALCANCERWHO","who");
   define("OTHER","Other");
   define("OTHERWHO","who");
   define("OVARIANCANCER","Ovarian cancer");
   define("OVARIANCANCERWHO","who");
   define("CHILDSNO","Childs no");
   define("PATTERN","pattern");
   define("AGEOFMARRIAGE","Age of marriage");
   define("PARTNERAGEATMARRIAGETIME","Partner age at marriage time");
   define("SMOKING","Smoking");
   define("SMOKINGCIGA","cigarette");
   define("SMOKINGCIGAR","cigar");
   define("SMOKINGWATERPIPE","water pipe");
   define("SMOKINGOPIUM","opium");
   define("SMOKINGCANNABIS","cannabis");
   define("SMOKINGHOWMUCH","how much(pack year)");
   define("OTHERSUBAGENT","Other substance agent");
   define("PERSONALINCOME","Personal income(Rial per month)");
   define("FAMILYINCOME","Family income(Rial per month)");
   define("LIFESTRESSOR","Life stressor");
   define("LIFESTRESSORWHAT","what");
   define("LIFESTRESSORTIME","time");
   define("HYPERLIPIDEMIA","Hyperlipidemia");
   define("HYPERLIPIDEMIAWHO","Who");
   define("MI","MI");
   define("MIWHO","Who");
   define("COM_FAMILY_AND_SOCIAL_HX"," ");
   define("FAMILY_REQUIRE_FIELDS","");   
   define("MSG_FAMILY_SAVE","Saving Successfully");   
   define("MSG_FAMILY_DELETE","Delete Successfully");
?>