<?php
   define("PREOPERATIVEID","id");
   define("BG","BG");
   define("RH","Rh");
   define("WBC","WBC (K)");
   define("RBC","RBC (M)");
   define("HB","Hb");
   define("HCT","Hct");
   define("MCV","MCV");
   define("MCH","MCH");
   define("PLATELET","Platelet (K)");
   define("NEUTROPHIL","Neutrophil %");
   define("LYMPH","Lymph%");
   define("EOSINOPHIL","Eosinophil%");
   define("BASOPHIL","Basophil%");
   define("BUN","BUN");
   define("TG","TG");
   define("TOTALCHOLESTEROL","Total Chol");
   define("HDL","HDL");
   define("LDL","LDL");
   define("ALT","ALT");
   define("AST","AST");
   define("ALKP","ALKP");
   define("CR","Cr");
   define("NA","Na");
   define("K","K");
   define("PT","PT");
   define("PTT","PTT");
   define("INR","INR");
   define("BLEEDINGTIME","Bleeding Time");
   define("FBS","FBS");
   define("TSH","TSH");
   define("URINECOR","24-hour urine cortisol");
   define("HIV","HIV");
   define("HBSAG","HBS Ag");
   define("HCVAB","HCV Ab");
   define("LIVER","Liver");
   define("LIVERSIZE","size");
   define("LIVERECHO","echo");
   define("LIVERFATTY","fatty liver");
   define("LIVERSOL","SOL");
   define("GB","GB");
   define("GBWALL","wall");
   define("GBDISTENDED","distended");
   define("GBSTONE","stone");
   define("SPLEEN","Spleen");
   define("SPLEENSIZE","size");
   define("SPLEENSOL","SOL");
   define("SPLEENSOLL","");
   define("UTERINE","Uterine");
   define("UTERINEENDOM","endometrial thickness");
   define("MYOMA","myoma");
   define("MYOMANO","no.");
   define("MYOMALOCA","Locations");
   define("MYOMASITUA","situation");
   define("OVARIES","Ovaries");
   define("OVARIESNECK","necklace pattern");
   define("CYST","cyst");
   define("CYSTNO","no.");
   define("CYSTSIZE","Size (mm)");
   define("CYSTSIDE","side");
   define("CYSTTEXTURE","texture");
   define("SCYSTSEP","septation");
   define("RKIDNEY","Right kidney");
   define("RKIDNEYSIZE","size (Cm)");
   define("RKIDNEYSTONE","stone");
   define("RKIDNEYSLUDGE","sludge");
   define("RKIDNEYCYST","cyst");
   define("LKIDNEY","Left kidney");
   define("LKIDNEYSIZE","size (Cm)");
   define("LKIDNEYSTONE","stone");
   define("LKIDNEYSLUDGE","sludge");
   define("LKIDNEYCYST","cyst");
   define("BLADDER","Bladder");
   define("BLADDERWALL","wall");
   define("BLADDERSTONE","stone");
   define("BLADDERMASS","mass");
   define("SONOGRAPHDESC"," ");
   define("ECGRATE","Rate");
   define("ECGRHYTHM","Rhythm");
   define("ECGQRS","QRS");
   define("ECGRR","RR");
   define("ECGQT","QT");
   define("ECGISCHEMIC","Ischemic signs");
   define("ECGDESCRIPTION","Description");
   define("CXRAIRWAY","Airway");
   define("CXRMEDI","Mediastina");
   define("CXRLUNG","lung field");
   define("CXRHEART","heart");
   define("CXRBONE","Bone");
   define("CXRLESION","solitary lesion");
   define("CXRCPA","CPA");
   define("CXRLOBE","upper lobe");
   define("CXRDES","Description");
   define("ENDOSCOPYES","Esophagus");
   define("ENDOSCOPYESWEB","web");
   define("ENDOSCOPYESSTR","stricture");
   define("ENDOSCOPYESLOC","location");
   define("ENDOSCOPYESNA","narrowing before distal sphincter");
   define("ENDOSCOPYESMU","mucosal lesion");
   define("ENDOSCOPYST","Stomach");
   define("ENDOSCOPYSTGA","gastritis");
   define("ENDOSCOPYSTPR","prominent fold");
   define("ENDOSCOPYSTUL","ulcer");
   define("ENDOSCOPYSTLO","locations");
   define("ENDOSCOPYSTPUT","RUT");
   define("ENDOSCOPYDU","Duodenum");
   define("ENDOSCOPYDUULCER","ulcer");
   define("ENDOSCOPYDURUT","RUT");
   define("ENDOSCOPYBIOPSY","Biopsy result");
   define("ENDOSCOPYBIOPSYRESDESC"," ");
   define("CARDIOREASON","Reason");
   define("CARDIORESULT","Result");
   define("PULMONOREASON","Reason");
   define("PULMONORESULT","Result");
   define("ANESTHESIOREASON","Reason");
   define("ANESTHESIORESULT","Result");
   define("GASTROENTREASON","Reason");
   define("GASTROENTRESULT","Result");
   define("NUTRITIONREASON","Reason");
   define("NUTRITIONRESULT","Result");
   define("PHYSIATREASON","Reason");
   define("PHYSIATRESULT","Result");
   define("ENDOCRINOREASON","Reason");
   define("ENDOCRINORESULT","Result");
   define("MULTICOMMITRE","Reason");
   define("MULTICOMMITPLAN","plan");
   define("MULTICOMMITKIND","kind of intervention");
   define("SYSTOLICBP","Systolic BP");
   define("DIASTOLICBP","Diastolic BP");
   define("MSXTG","TG");
   define("MSXHDL", "HDL");
   define("MSXFBS", "FBS");
   define("MSXWCF", "WCF");
   define("COM_PREOPERATIVE"," ");
   define("PREOPERATIVE_REQUIRE_FIELDS","");
   define("MSG_PREOPERATIVE_SAVE","Saving Successfully");
   define("MSG_PREOPERATIVE_DELETE","Delete Successfully");
?>

