<?php define("IDENTICAL_DATAID","Id");
   define("DATE","Date");
   define("COMFILENO","Computer File No");
   define("NAME","Name");
   define("LNAME","Last name");
   define("ENGNAME","English Name");
   define("FATHER","Name of father");
   define("NATIONALID","National ID");
   define("AGE","Age");
   define("SEX","Gender");
   define("MARITALSTATUS","Marital Status");
   define("HOMETEL","Home tel. no");
   define("MOBILENO","Mobile no");
   define("CLOSERELTELNO","Close relative tel. no");
   define("ADDRESS","Address");
   define("EMAIL","Email");
   define("EDUCATION","Education");
   define("OCCUPATION","Occupation");
   define("NATIONALITY","Nationality");
   define("PREVUNDIETS","Previous Unsuccessfull diets");
   define("INABILITYEXER","Inability to exercise");
   define("ARTHRITIS","Arthritis");
   define("ASTHMA","Asthma");
   define("HEARTPALP","Heart Palpitations");
   define("INFERTILITY","Infertility");
   define("INTERNALDIS","Internal Diseases");
   define("BEAUTYPERSONAL","Beauty and personal reasons");
   define("BIRTHPLACE","Birth Place");
   define("REFROUTE","Referral Route");
   define("RESPHYSICIAN","Responsible Physician");
   define("ISOPERATED","Operated");
   define("IDENTICAL_REQUIRE_FIELDS","name,lname,age,sex,date,nationalid");
   define("MSG_IDENTICAL_SAVE","Saving Successfully");
   define("MSG_IDENTICAL_DELETE","Delete Successfully");
?>