<?php
   define("REVIEW_OF_SYSTEMSID","id");
   define("CHESTPAINEOEX","Chest pain on exertion");
   define("PALPITATION","Palpitation");
   define("PAROXYSMALNODY","Paroxysmal nocturnal dyspnea");
   define("ORTHOPNEA","Orthopnea");
   define("EDEMA","Edema");
   define("EDEMAGENERALIZED","generalized");
   define("EDEMAPEDAL","Pedal");
   define("DYSPNEA","Dyspnea");
   define("DYSPNEAONEXERTION","on exertion");
   define("DYSPNEAEVENING","evening");
   define("DYSPNEASLEEP","sleep");
   define("DYSPNEARELATEDTOPILLOW","related to pillow");
   define("DYSPNRELIEF","Relief by bronchodilators");
   define("SNORING","Snoring");
   define("YAWING","Yawing");
   define("SOMNOLENCE","Somnolence");
   define("FREPUENTNOSLAR","frequent nocturnal sleep arousal");
   define("VOICECHANGE","Voice change");
   define("VOICECHANGENASAL","nasal");
   define("VOICECHANGEHOARSENESS","hoarseness");
   define("CHRONICCOUGH","Chronic cough");
   define("CHRONICCOUGHEXAATNIGHTS","exaggeration at nights");
   define("CHRONICCOUGHWITHSPPRO","with sputum production");
   define("HARSHAURES","Harsh audibly respiration");
   define("HARSHAURESWITHINEXAG","with intermittent exaggeration");
   define("HARSHAURESRELIEFBYBR","relief by bronchodilators");
   define("CHESTCONSEN","Chest constriction sensation");
   define("CHESTCONSENWITHEXAATEVENING","with exaggeration at evening");
   define("CHESTCONSENRELIEFBYBR","relief by bronchodilators");
   define("RECHESTPAIN","Retrosternal chest pain");
   define("RECHESTPAINSOON","soon");
   define("RECHESTPAINHOUR","2-3 hour");
   define("RECHESTPAINPOSTPRANDIAL","postprandial");
   define("RECHESTPAINSUPPOS","supine position");
   define("RECHESTPAINNOCTURNAL","nocturnal");
   define("SOURMATERIALRE","Sour material regurgitation");
   define("SOURMATERIALREPOST","postprandial");
   define("SOURMATERIALRESUPPOS","supine position");
   define("SOURMATERIALRENOC","nocturnal");
   define("HEARTBURN","Heart burn");
   define("HEARTBURNPOST","postprandial");
   define("HEARTBURNSUPPOS","supine position");
   define("HEARTBURNNOC","nocturnal");
   define("POSTEQIPAIN","Postprandial epigastric pain");
   define("REOFDIWITHAN","Relieve of discomforts with antacids");
   define("RUQDISCOMFORT","RUQ discomfort");
   define("RUQDISCOMFORTRETOME","related to meals(esp. fatty meal)");
   define("POSTRISHPAIN","Postprandial right shoulder pain(esp. after fatty meal)");
   define("CONSTIPATION","Constipation");
   define("DIARRHEA","Diarrhea");
   define("INTBETDIACON","Interchange between diarrhea & constipation");
   define("ICTERUS","Icterus");
   define("ICTERUSSHORTEP","short episode with fasting/fever");
   define("ICTERUSPROLONGED","prolonged");
   define("ICTERUSACCOWITH","accompanied with urine color change");
   define("NAUSEA","Nausea");
   define("VOMITING","Vomiting");
   define("DYSCHEZIA","Dyschezia");
   define("HEMATOCHEZIA","Hematochezia");
   define("BLOODYSTONST","Bloody streaks on stool");
   define("LUMPSENONPER","Lump sensation on perianal area");
   define("LUMPSENONPERAFTER","after defecation");
   define("LUMPSENONPERSPONT","spontaneous resolution");
   define("DIFFICULTY","Difficulty with evacuation");
   define("SENSEOFREFUL","Sense of rectum fullness after defecation");
   define("LUNPORMASS","Lump or mass");
   define("LUNPORMASSING","Inguinal");
   define("LUNPORMASSFEMORAL","femoral");
   define("LUNPORMASSUM","umbilical");
   define("LUNPORMASSAN","Anterior of Abdomen scrotum");
   define("LUNPORMASSREWITHSLIGHT","Reduction with slight pressure");
   define("LUNPORMASSREWITHSUPINE","reduction with supine position");
   define("LUNPORMASSEXAC","Exacerbating with activity or valsalva maneuver");
   define("DISWITHACT","Discomfort with activity");
   define("DISWITHACTINGUINAL","inguinal");
   define("DISWITHACTUMBILICAL","umbilical");
   define("DISWITHACTANTERIOR","Anterior of Abdomen");
   define("DISWITHACTSCROTUM","scrotum");
   define("BONEPAINE","Bone pain");
   define("BONEPAINEGENE","generalized");
   define("BONEPAINEOTHER","other");
   define("LOWBACKPAIN","Low back pain");
   define("LOWBACKPAININSUPINE","in supine");
   define("LOWBACKPAINONST","on standing");
   define("LOWBACKPAINWITHWA","with walking");
   define("LOWBACKPAINRAD","Radiation");
   define("LOWBACKPAINBUTTOCK","buttock");
   define("LOWBACKPAINTHIGH","thigh");
   define("LOWBACKPAINFOOT","foot");
   define("HIPPAIN","Hip pain");
   define("HIPPAINEXACERBATION","exacerbation with up staring");
   define("HIPPAINWITH","with walking");
   define("HIPPAINRELIEVE","relieve by rest");
   define("KNEEPAIN","Knee pain");
   define("KNEEPAINEXAGG","exaggeration with walking");
   define("KNEEPAINRELIEVE","relieve with resting");
   define("KNEEPAINCREP","crepitation");
   define("KNEEPAINSWELLING","swelling with overuse");
   define("KNEEPAINLEG","Leg pain with prolonged standing");
   define("FIRSTMEPAIN","First metatarsophalangeal joint pain");
   define("FIRSTMEPAININT","intermittently");
   define("FIRSTMEPAINNIGHT","night attacks");
   define("FIRSTMEPAINWARMNESS","warmness");
   define("FIRSTMEPAINREDNESS","redness");
   define("FIRSTMEPAINSWELLING","swelling");
   define("ANKLEPAINE","Ankle pain");
   define("ANKLEPAINEINTER","intermittently");
   define("ANKLEPAINENIGHT","night attacks");
   define("ANKLEPAINEWARM","warmness");
   define("ANKLEPAINERED","redness");
   define("ANKLEPAINESWE","swelling");
   define("WEAKNESS","Weakness");
   define("WEAKNESSGENE","generalized");
   define("WEAKNESSONCOMBING","on combing");
   define("WEAKNESSONSTAND","on standing");
   define("WEAKNESSWRITING","writing");
   define("FATIGUE","Fatigue");
   define("FATIGUEALLDAY","all day long");
   define("FATIGUEEVENING","evening");
   define("FATIGUEAFTERPH","after physical activity");
   define("BLURREDVISION","Blurred vision");
   define("BLURREDVISIONINTER","intermittent");
   define("BLURREDVISIONWITHHE","with headache");
   define("DIPLOPIA","Diplopia");
   define("TUNNELVISION","tunnel vision");
   define("SCOTOMA","scotoma");
   define("TINNITUS","Tinnitus");
   define("IMPAIREDHEARING","Impaired hearing");
   define("PARINMEDIAN","Paresthesia in median N. territory");
   define("PARINLAT","Paresthesia in lat. cut. N. of thigh territory");
   define("HEADACHE","Headache");
   define("HEADACHEMORNING","morning");
   define("HEADACHEEVENING","evening");
   define("HEADACHESLEEP","sleep");
   define("HEADACHEPULSATILE","pulsatile");
   define("HEADACHEAURA","aura");
   define("HEADACHELOCATEDIN","Located in frontal");
   define("HEADACHEOCCIPITAL","occipital");
   define("HEADACHEHEM","hemicranial");
   define("HEADACHEGENERA","generalized");
   define("HEADACHEFACIUM","facium");
   define("HEADACHEBITEM","bitemporal");
   define("HEADACHEACCOM","Accompanied with N/V");
   define("HEADACHEPHOTO","photophobia");
   define("HEADACHERELIEVEWITH","relieve with sleep");
   define("INSOMNIA","Insomnia");
   define("HYPERSOMNIA","Hypersomnia");
   define("EARLYSTANDING","Early standing up");
   define("PSYCHOMOTOR","Psychomotor agitation");
   define("DIFFIINCON","Difficulty in concentration");
   define("DIMIINALL","Diminished interest in almost all activity");
   define("DEPRESSEDMOOD","Depressed mood");
   define("FEELINGOFGUILT","Feeling of inappropriate guilt");
   define("SADNESS","Sadness");
   define("IRRITABILITY","Irritability");
   define("INDIFFERENCE","Indifference or apathy");
   define("ANERGY","Anergy");
   define("PANICATTAK","Panic attak");
   define("PANICATTAKPOUNDING","Pounding heart");
   define("PANICATTAKSWEAT","sweating");
   define("PANICATTAKTREMBL","trembling");
   define("PANICATTAKSHORTNESS","shortness of breath");
   define("PANICATTAKGLOBUS","globus hystericus");
   define("PANICATTAKCHEST","Chest discomfort");
   define("PANICATTAKABDOMINAL","Abdominal distress");
   define("PANICATTAKDIZZY","Dizzy");
   define("PANICATTAKDEREA","Derealization");
   define("PANICATTAKDEPER","Depersonalization");
   define("PANICATTAKDYING","Fear of dying");
   define("PANICATTAKCRAZY","Fear of going crazy");
   define("PANICATTAKPARES","Paresthesia");
   define("PANICATTAKCHILLS","Chills");
   define("PANICATTAKHOT","Hot flushes");
   define("DIFFIINWORRY","Difficulty in controlling worry, accompanied with");
   define("DIFFIINWORRYREST","Restlessness");
   define("DIFFIINWORRYBECOMING","becoming easily fatigue");
   define("DIFFIINWORRYSLEEP","Sleep disturbance");
   define("DIFFIINWORRYINFALLING","Difficulty in falling sleep");
   define("DIFFIINWORRYINSTAYING","Difficulty in staying sleep");
   define("DIFFIINWORRYUNSATISFYING","unsatisfying sleep");
   define("AGORAPHOBIA","Agoraphobia");
   define("POORSELFESTEEM","Poor self esteem");
   define("OTHERPHOBIA","Other phobia");
   define("OTHERPHOBIAOTHER","Other phobia");
   define("OBSESSION","Obsession");
   define("OBSESSIONCONTAMINATION","contamination");
   define("OBSESSIONWASHING","washing");
   define("OBSESSIONCHECKING","checking");
   define("OBSESSIONCOUNTING","counting");
   define("OBSESSIONOTHER","other");
   define("IMPAIREDATTITUDE","Impaired attitude");
   define("IMPAIREDATTITUDEWEIGHT","toward body weight");
   define("IMPAIREDATTITUDESHAPE","toward body shape");
   define("ISOYELLDIS","Isolated yellowish discoloration of palm and soles");
   define("ISOYELLDISESP","esp. after fruit consumption");
   define("DRYSKIN","Dry skin");
   define("COARSESKIN","Coarse skin");
   define("HIRSUTISM","Hirsutism");
   define("HIRSUTISMFACE","face");
   define("HIRSUTISMCHEST","chest");
   define("HIRSUTISMABDOMEN","abdomen");
   define("HIRSUTISMBACK","back");
   define("HIRSUTISMEXTREMITY","extremity");
   define("HAIRLOSS","Hair loss");
   define("HAIRLOSSDIFFUSE","diffuse");
   define("HAIRLOSSSCALP","scalp");
   define("HAIRLOSSEYEBROW","localized eyebrow");
   define("HAIRLOSSOTHERAREA","localized other area");
   define("DARKOFSKINFOLDS","Darkening of skin folds");
   define("NAILPROBLEM","Nail problem");
   define("BRUISABILITY","Easy bruisability");
   define("PROBLEEDING","Prolonged bleeding (>few minutes)");
   define("DEWOUNDHEALING","Delayed wound healing (>few days)");
   define("MACANDREDNESS","Maceration and redness in body folds");
   define("ACNE","Acne");
   define("COLDINTOLERANCE","Cold intolerance");
   define("ALTEREDLIBIDO","Altered libido");
   define("ALTEREDLIBIDOTYPE","type");
   define("IMPOTENCE","Impotence");
   define("POLYURIA","Polyuria");
   define("POLYDIPSIA","Polydipsia");
   define("MENARCHE","Menarche");
   define("MENARCHEAGE","age");
   define("MENOPAUSE","Menopause");
   define("MENOPAUSEAGE","age");
   define("AMENORRHEA","Amenorrhea");
   define("AMENORRHEATYPE","type");
   define("LMP","LMP");
   define("REGULARCYCLE","Regular cycle");
   define("REGULARCYCLELENGTH","length(day)");
   define("REGULARCYCLEDURATION","duration of mensturation(day)");
   define("IRREGULARCYCLE","Irregular cycle");
   define("IRREGULARCYCLEOLIGOM","oligomenorrhea");
   define("IRREGULARCYCLEPOLY","polymenorrhea");
   define("IRREGULARCYCLEHYPER","hypermenorrhea");
   define("IRREGULARCYCLEHYPOM","hypomenorrhea");
   define("IRREGULARCYCLEMENOR","menorrhagia");
   define("SPOTTING","Spotting");
   define("SPOTTINGPRE","premenstrual");
   define("SPOTTINGPOST","postmenstrual");
   define("SPOTTINGINTER","intercycle");
   define("DYSMENORRHEADYS","Dysmenorrhea");
   define("DYSMENORRHEAPRI","primary");
   define("DYSMENORRHEASEC","secondary");
   define("DYSMENORRHEAPREM","Premenstrual (1-2 days)");
   define("DYSMENORRHEAONSET","onset before menstruation (few days and more)");
   define("DYSMENORRHEAAT","At the onset of menstruation");
   define("DYSMENORRHEARELIEF","relief by the onset menstrual flow");
   define("DYSPAREUNIA","Dyspareunia");
   define("DIFFICONCEIVING","Difficulty in conceiving");
   define("DIFFICONCEIVINGP"," ");
   define("RECMISCARRIAGE","Recurrent miscarriage (>2 times)");
   define("VAGDISCHARGE","Vaginal discharge");
   define("VAGDISCHARGECOLOR","colorless");
   define("VAGDISCHARGEWHIT","whitish");
   define("VAGDISCHARGEYELL","yellow");
   define("VAGDISCHARGEBLO","bloody");
   define("VAGDISCHARGEGREEN","green");
   define("VAGDISCHARGEMAL","malodor");
   define("VAGDISCHARGEITCHING","itching");
   define("BRMASE","Breast mass sensation");
   define("BRMASECYCLIC","cyclic");
   define("MASTALGIA","Mastalgia");
   define("MASTALGIACYCLIC","cyclic");
   define("MASTALGIASIDE","side");
   define("GALACTORRHEA","Galactorrhea");
   define("GALACTORRHEASIDE","side");
   define("OTHERNIPPLE","Other nipple discharge");
   define("INCONTINENCE","Incontinence");
   define("INCONTINENCETYPE","type");
   define("REVIEW_OF_SYSTEM_DESC","");
   define("REVIEW_REQUIRE_FIELDS","ident_id,review_of_systemsid");
   define("MSG_REVIEW_SAVE","Saving Successfully");
   define("MSG_REVIEW_DELETE","Delete Successfully");
?>