<?php
   define("DIETID","id");
   define("ONSETGAIN","Onset of weight gain (age)");
   define("ACCELERATEDP","accelerated periods(age/event)");
   define("BREAKFAST","Breakfast");
   define("BREAKFASTTIME","time");
   define("BREAKFASTWHAT","what");
   define("LUNCH","Lunch");
   define("LUNCHTIME","time");
   define("LUNCHWHAT","what");
   define("DINNER","Dinner");
   define("DINNERTIME","time");
   define("DINNERWHAT","what");
   define("OTHERMM","Other main meal");
   define("OTHERMMTIME","time");
   define("OTHERMMWHAT","what");
   define("SNACKBEBRLU","Snack between breakfast and lunch");
   define("SNACKBEBRLUNO","no.");
   define("SNACKBEBRLUWHAT","What");
   define("SNACKBEBRLUTIME","times");
   define("SNACKBELUDI","Snack between lunch and dinner");
   define("SNACKBELUDINO","no.");
   define("SNACKBELUDIWHAT","What");
   define("SNACKBELUDITIME","times");
   define("BREAKFASTMORE","Breakfast more than usual");
   define("LUNCHMORE","Lunch more than usual");
   define("DINNERMORE","Dinner more than usual");
   define("BINGE","Binge");
   define("BINGEDIETING","after dieting");
   define("BINGETV","with TV");
   define("BINGESTUDY","with studying");
   define("BINGEHOMEWORK","with home working");
   define("BINGENET","with net surfing");
   define("BINGEPLAYING","with game playing");
   define("BINGEATJOB","at job");
   define("BINGEEMOTION","with emotion");
   define("BINGESAD","sadness");
   define("BINGEANGER","anger");
   define("BINGEHAPPINESS","happiness");
   define("BINGENERVOUS","nervousness");
   define("BINGELOSSCONTROL","with loss of control");
   define("BINGEHUNGER","without hunger");
   define("BINGEFREQUENCY","Frequency of binge");
   define("RAPIDLYEATING","Eating more rapidly than normal");
   define("FULLEATING","Eating until feeling uncomfortably full");
   define("EMBARRASSMENTEAT","Eating alone because of embarrassment by the amount of food consumed");
   define("OVEREATING","Feeling disgusted with oneself, depressed, or guilty after overeating");
   define("SWEATLOVER","Sweat lover");
   define("BREADRICE","Bread and rice");
   define("POTATOCHIPS","Potato Chips");
   define("FASTFOOD","FastFood");
   define("TEA","Tea");
   define("CHOCALATELOVER","chocalate lover");
   define("ICECREAMLOVER","ice cream lover");
   define("CARBONATEDBEVER","regular carbonated beverage consumption");
   define("PURGE1","Purge");
   define("PURGEVOMIT","Inducing vomiting");
   define("PURGEABUSE","laxative abuse");
   define("PURGEDIURETIC","diuretic abuse");
   define("PURGEOVERUSE","Levothyroxine overuse");
   define("PURGEANT","antidiabetics overuse");
   define("PURGEINTENSE","intense exercise");
   define("WEIGHTDIET","Followed a weight reduction diet");
   define("WEIGHTDIETWHAT","What kind");
   define("WEIGHTDIETHOWLONG","How long");
   define("WEIGHTDIETDATETYPE","Priod");
   define("WEIGHTDIETSUCCESS","How success(kg)");
   define("ALCOHOLCONS","Alcohol consumption");
   define("ALCOHOLCONSWHAT","What kind");
   define("ALCOHOLCONSFREQUENT","Frequency");
   define("ALCOHOLCONSHOWMUCH","How much (cup/episode)");
   define("ALCOHOLCONSHOWMUCH1","");
   define("WALKING","Walking");
   define("WALKINGHOME","only home jobs");
   define("WALKINGWORK","work related");
   define("WALKINGHABITUAL","habitual");
   define("WALKINGFRE","frequency");
   define("WALKINGFRE1","");
   define("WALKINGDURATION","duration");
   define("WALKINGDURATION1","");
   define("SPORTACTIVITY","Sport activity");
   define("SPORTACTIVITYWHAT","What kind");
   define("SPORTACTIVITYF","frequency");
   define("SPORTACTIVITYF1","");
   define("SPORTACTIVITYD","duration");
   define("SPORTACTIVITYD1","");
   define("SPORTACTIVITYTIME","Time of initiation");
   define("PPHYSICAL","Past physical activity");
   define("PPHYSICALWHAT","What kind");
   define("PPHYSICALFRE","frequency");
   define("PPHYSICALFRE1","");
   define("PPHYSICALDU","duration");
   define("PPHYSICALDU1","");
   define("PPHYSICALREASON","Reason for termination:");
   define("PALSE","PAL");
   define("PHYSICALDESC"," ");
   define("COM_DIET"," ");
   define("DIET_REQUIRE_FIELDS","");
   define("MSG_DIET_SAVE","Saving Successfully");
   define("MSG_DIET_DELETE","Delete Successfully");
?>