<?php
   define("PMHXID","id");
   define("DM","DM");
   define("DMTYPE","type");
   define("DMWHEN","when");
   define("HYPERLIPIDEMIA","Hyperlipidemia");
   define("HYPERLIPIDEMIAWHEN","when");
   define("TYROIDDY","Thyroid dysfunction");
   define("TYROIDDYWHEN","when");
   define("HTN","HTN");
   define("HTNWHEN","when");
   define("CAD","CAD");
   define("CADWHEN","when");
   define("CKD","CKD");
   define("CKDWHEN","when");
   define("CKDCAUSE","Cause");
   define("CHF","CHF");
   define("CHFWHEN","when");
   define("CVA","CVA");
   define("CVAWHEN","when");
   define("DVT","DVT");
   define("DVTWHEN","when");
   define("DVTPULMONARY","Pulmonary emboli");
   define("ASTHMA","Asthma");
   define("ASTHMAWHEN","when");
   define("ATOPIA","Atopia");
   define("ATOPIARHINITIS","allergic rhinitis");
   define("SLIMMING", "Slimming");
   define("ATOPIACONJUNC","allergic conjunctivitis");
   define("ATOPIAECZEMA","eczema");
   define("ATOPIAANAPHYLAXIS","anaphylaxis");
   define("ATOPIANASAL","nasal polyp");
   define("ATOPIADRUG","drug");
   define("ATOPIAFOOD","food");
   define("ATOPIABITE","bite");
   define("ATOPIAENVIRONMENT","environmental");
   define("ATOPIAWHEN","when");
   define("SLEEPAPNEA","Sleep apnea");
   define("SLEEPAPNEAWHEN","when");
   define("FATTYLIVER","Fatty liver");
   define("FATTYLIVERWHEN","when");
   define("PUD","PUD");
   define("PUDWHEN","when");
   define("GERD","GERD");
   define("GERDWHEN","when");
   define("GIBLEEDING","GI bleeding");
   define("GIBLEEDINGTYPE","type");
   define("GIBLEEDINGWHEN","when");
   define("HEPATITIS","Hepatitis");
   define("HEPATITISWHEN","when");
   define("GALLSTONE","Gallstone");
   define("GALLSTONEWHEN","when");
   define("CHOLEDOLITHIASIS","Choledocholithiasis");
   define("CHOLEDOLITHIASISWHEN","when");
   define("GOUT","Gout");
   define("GOUTWHEN","when");
   define("INFERTILITY","Infertility");
   define("INFERTILITYPRI"," ");
   define("CUSHING","Cushing");
   define("CUSHINGWHEN","when");
   define("DEPRESSION","Depression");
   define("DEPRESSIONWHEN","when");
   define("ANXIETYDIS","Anxiety disorders");
   define("ANXIETYDISWHEN","when");
   define("PERDISORDERS","Personality disorders");
   define("PERDISORDERSWHEN","when");
   define("PSYDISORDERS","Psychotic disorders");
   define("PSYDISORDERSWHEN","when");
   define("CHD","CHD");
   define("PREVIOUSSUR","Previous surgery");
   define("PREVIOUSSURWHAT","what kind");
   define("PREVIOUSSURADHESION","Adhesion band compatible history");
   define("DISEASEOTHER","Other");
   define("KNOWNPRE","know prenatal event");
   define("KNOWNPRELBW","LBW");
   define("KNOWNPREIUGR","IUGR");
   define("KNOWNPREGDMINMOTHER","GDM in mother");
   define("KNOWNPREPOSTTERM","postterm");
   define("KNOWNPREPRETERM","preterm");
   define("KNOWNPREBIRTH","Birth weight");
   define("KNOWNPREHYPER","Hyperbilirubinemia");
   define("KNOWNPREASPHYXIA","Asphyxia");
   define("KNOWNPREPRODUCT","Product of");
   define("KNOWNPREBIR","birth month");
   define("KNOWNPREDESC"," ");
   define("G","G");
   define("A","A");
   define("P","P");
   define("L","L");
   define("GDMSEX","(G# DM/HTN dx/PROM/PLP/Steatohepatosis/GCM G.A.abort,stillbirth,NVD,C/S,episiotomy Sex exclusive breastfeeding/Nursing duration)");
   define("ANTIPSYCHOTICS","Antipsychotics");
   define("GLUCOCO","Glucocorticoids");
   define("LITHIUM","Lithium");
   define("PROGESTIN","Progestin");
   define("TCA","TCA");
   define("ESTROGEN","Estrogen");
   define("SSRI","SSRI");
   define("OCP","OCP");
   define("OTHERANTIDEPRESSANT","Other antidepressant");
   define("NSAID","NSAID");
   define("ANTICONVULSANT","Anticonvulsant");
   define("WARFARIN","Warfarin");
   define("ANTIDIABETIC","Antidiabetic");
   define("LMWH","LMWH");
   define("SEROTONINHISTAMINE","Serotonin and histamine antagonist");
   define("OTHERRR","Other");
   define("OTHERDESC"," ");
   define("BETABLOCKERS","Beta blockers");
   define("DRUGDESC"," ");
   define("PREVPARADESC"," ");
   define("PMHX_REQUIRE_FIELDS","");
   define("MSG_PMHX_SAVE","Saving Successfully");
   define("MSG_PMHX_DELETE","Delete Successfully");
?>
