<?php
   define("PEID","id");
   define("GROSSBODY","Gross body shape");
   define("OBESITYTYPE","Obesity type");
   define("RESDISTRESS","Respiratory distress");
   define("CYANOSIS","Cyanosis");
   define("PALLOR","Pallor");
   define("CRIPPLE","Cripple");
   define("CRIPPLECANE","cane");
   define("CRIPPLEWALKER","walker");
   define("CRIPPLEWHEEL","wheelchair");
   define("CRIPPLEBEDRIDDEN","bedridden");
   define("WELLBEING","Wellbeing");
   define("WELLBEINGHEALTH","healthy appearance");
   define("WELLBEINGMILDLY","mildly ill appearance");
   define("WELLBEINGILL","severely ill");
   define("PICKAPPEAR","Pickwickian appearance");
   define("MOONFACED","Moonfaced");
   define("ACROMEGALIC","Acromegalic");
   define("MYXEDEMATOUS","Myxedematous");
   define("SUPTAFAT","Supra clavicular fat deposition");
   define("RETROCERVICAL","retrocervical fat deposition");
   define("SYSTOLIC","systolic BP");
   define("DIASTOLIC","diastolic BP");
   define("PULSE","Pulse");
   define("RESPIRATION","Respiration");
   define("TEMP","Temp");
   define("WEIGHT","Weight (Kg)");
   define("MIDAXILLA","Midaxilla SF");
   define("HEIGHT","Height (Cm)");
   define("ABDOMENSF","Abdomen SF");
   define("BMI","BMI");
   define("SUPRAILIAC","Suprailiac SF");
   define("MAC","MAC");
   define("QUADRICEPS","Quadriceps SF");
   define("TSF","TSF");
   define("WAISTCIR","Waist circumference (Cm)");
   define("PECTORAL","Pectoral SF");
   define("HIPCIR","Hip circumference (Cm)");
   define("SUBSCAPULA","Subscapula SF");
   define("FATPERCENT","Body fat percentage");
   define("METHOD","method");
   define("PALECONJUNC","Pale conjunctiva");
   define("ICTERICSCLERA","Icteric sclera");
   define("EXOPHTHA","Exophthalmos");
   define("CORNEAL","Corneal arcus");
   define("CORNEALRATIO","ratio");
   define("CORNEALTHICK","thickness");
   define("XANTHEL","Xanthelasma");
   define("XANTHELMILI","miliary");
   define("XANTHELPATCHY","patchy");
   define("XANTHELUPPER","upper lid");
   define("XANTHELLOWER","lower lid");
   define("XANTHELMED","med canthus");
   define("LOBEAR","Lobulated ear");
   define("LOBEARDAR","Darwin�s tubercle");
   define("LOBEARCREASE","Ear Crease");
   define("LOBEARTAG","Ear Tag");
   define("ANGULAR","Angular cheilitis");
   define("GLOSSITIS","Glossitis");
   define("GLOSSITISATR","atrophic");
   define("GLOSSITISFIS","fissured");
   define("GLOSSITISGEO","geographic");
   define("GLOSS","Glossomegaly");
   define("GLOSSPRO","protruded");
   define("GLOSSEN","enlarged");
   define("GLOSSONLY","only dental impression");
   define("MICROGNATHIA","Micrognathia");
   define("THYROMEGALY","Thyromegaly");
   define("THYROMEGALYGRADE","grade");
   define("SHORTNECK","Short neck");
   define("HEARTSE","Heart sound evaluated");
   define("HEARTSENORM","Normal");
   define("HEARTSEMUFF","Muffled");
   define("HEARTSEMURMUR","Murmur");
   define("HEARTSESS","S3");
   define("HEARTSESSS","S4");
   define("HEARTSEFRIC","Friction rub");
   define("LUNGAU","Lung auscultation");
   define("LUNGAURESP","respiration sound");
   define("LUNGAURALES","Rales");
   define("LUNGAUWHEEZ","Wheeze");
   define("LUNGAUEGOP","Egophonia");
   define("LUNGAUTACTILE","Tactile fremitus");
   define("CHESTIN","Chest inspection");
   define("CHESTINASY","Asymmetry in expansion");
   define("CHESTINSCO","scoliosis");
   define("CHESTINKYP","kyphosis");
   define("BREXAM","Breast exam");
   define("BREXAMMASS","Mass detected");
   define("BREXAMLOCAT","location");
   define("BREXAMSIZE","size (Cm)");
   define("BREXAMTEND","tenderness");
   define("BREXAMCONSIST","Consistency");
   define("BREXAMMOBI","Mobility");
   define("BREXAMPEAU","Peau d orange");
   define("BREXAMSKIN","skin retraction");
   define("BREXAMAXI","accompanied axillary LAP");
   define("ABDOMSHAP","Abdominal Shape");
   define("SCAROF","Scar of surgery");
   define("SCAROFWHAT","what");
   define("CAPUTME","Caput medusa");
   define("PALPMASS","Palpatable mass");
   define("PALPMASSEPIG","epigastric");
   define("PALPMASSUMB","umbilical");
   define("PALPMASSING","inguinal");
   define("PALPMASSFEM","femoral");
   define("PALPMASSSCR","scrotal");
   define("PALPMASSFLANK","flank");
   define("PALPMASSREDU","Reducable");
   define("PALPMASSTENDER","tenderness");
   define("PALPMASSSITU","situation");
   define("TENDERNESSTEN","Tenderness");
   define("TENDERNESSLOC","location");
   define("TENDERNESSMUR","murphy");
   define("LIVERSPAN","Liver span");
   define("LIVERSPANTEX","Liver span");
   define("SPLENOMEGALY","Splenomegaly");
   define("DULLNESS","Shifting dullness");
   define("RECTALEXAM","Rectal exam");
   define("RECTALEXAMHEM","hemorrhoid");
   define("RECTALEXAMFISS","fissure");
   define("RECTALEXAMCLOCK","clock");
   define("EXPULSE","Pulse");
   define("EXEDEMA","Edema");
   define("EDEMATYPE","type");
   define("DEFORMITY","Deformity");
   define("DEFORMITYWHAT","what kind");
   define("VARVEIN","Varicose vein");
   define("JOINTABNORM","joint abnormality");
   define("JOINTABNORMW","what");
   define("JOINTABNORMSW","swelling");
   define("JOINTABNORMCRE","crepitation");
   define("JOINTABNORMRED","redness");
   define("JOINTABNORMWARM","warmth");
   define("JOINTABNORMPAIN","pain at motion");
   define("TOPHUSFOOT","Tophus in foot");
   define("NAILCHANGE","Nail change");
   define("NAILCHANGEW","what");
   define("NAILCHANGEDISFI","Distal finger exfoliation");
   define("STRIAE","Striae");
   define("STRIAECOLOR","color");
   define("STRIAELOCAT","location");
   define("ACNE1","Acne");
   define("ACNEFACE","face");
   define("ACNENECK","neck");
   define("ACNECHEST","chest");
   define("ACNEBACK","back");
   define("INTERTRIGO","Intertrigo");
   define("INTERTRIGOAXI","axillae");
   define("INTERTRIGOINF","inframammary");
   define("INTERTRIGOINT","intergluteal");
   define("INTERTRIGOABD","abdominal fold");
   define("ACANNIG","Acanthosis nigricans");
   define("ACANNIGAXILLAE","axillae");
   define("ACANNIGNECK","neck back");
   define("ACANNIGSIDES","neck sides");
   define("ACANNIGINGUINAL","inguinal");
   define("ACANNIGINFR","inframammary");
   define("ACANNIGFINGERS","back of fingers");
   define("LEGULCER","Leg ulcer");
   define("LEGULCERMEDIAL","medial malleus");
   define("LEGULCERLATERAL","lateral malleus");
   define("LEGULCERFINGER","distal finger");
   define("LEGULCERTIBIAL","anterior of tibial");
   define("LEGULCERSOLE","sole");
   define("SKINTAGS","Skin tags");
   define("SKINTAGSLOC","location");
   define("XANTHOMA","Xanthoma");
   define("XANTHOMAERU","eruptive");
   define("XANTHOMATEN","tendon");
   define("XANTHOMAEXT","extensor surface");
   define("XANTHOMALOCA","location");
   define("YELLOWPANDS","Yellow palm and soles");
   define("SKINDESC"," ");
   define("COM_PE"," ");
   define("PE_REQUIRE_FIELDS","");
   define("MSG_PE_SAVE","Saving Successfully");
   define("MSG_PE_DELETE","Delete Successfully");
?>

