<?php
   define("FUID","id");
   define("OBESITYCLIVISIT"," ");
   define("POSTOP1W"," ");
   define("POSTOP2W"," ");
   define("POSTOP3W"," ");
   define("POSTOP4W"," ");
   define("POSTOP2M"," ");
   define("POSTOP3M"," ");
   define("POSTOP4M"," ");
   define("POSTOP5M"," ");
   define("POSTOP6M"," ");
   define("REDUCED1W"," ");
   define("REDUCED2W"," ");
   define("REDUCED3W"," ");
   define("REDUCED4W"," ");
   define("REDUCED2M"," ");
   define("REDUCED3M"," ");
   define("REDUCED4M"," ");
   define("REDUCED5M"," ");
   define("REDUCED6W"," ");
   define("POSTOP7M"," ");
   define("POSTOP8M"," ");
   define("POSTOP9M"," ");
   define("POSTOP10M"," ");
   define("POSTOP11M"," ");
   define("POSTOP12M"," ");
   define("POSTOP13M"," ");
   define("POSTOP14M"," ");
   define("POSTOP15M"," ");
   define("REDUCED7M"," ");
   define("REDUCED8M"," ");
   define("REDUCED9M"," ");
   define("REDUCED10M"," ");
   define("REDUCED11M"," ");
   define("REDUCED12M"," ");
   define("REDUCED13M"," ");
   define("REDUCED14M"," ");
   define("REDUCED15W"," ");
   define("POSTOP16M"," ");
   define("POSTOP17M"," ");
   define("POSTOP18M"," ");
   define("POSTOP19M"," ");
   define("POSTOP20M"," ");
   define("POSTOP21M"," ");
   define("POSTOP22M"," ");
   define("POSTOP23M"," ");
   define("POSTOP24M"," ");
   define("REDUCED16M"," ");
   define("REDUCED17M"," ");
   define("REDUCED18M"," ");
   define("REDUCED19M"," ");
   define("REDUCED20M"," ");
   define("REDUCED21M"," ");
   define("REDUCED22M"," ");
   define("REDUCED23M"," ");
   define("REDUCED24W"," ");
   define("SYSTOLICBP3M"," ");
   define("SYSTOLICBP9M"," ");
   define("SYSTOLICBP1Y"," ");
   define("SYSTOLICBP2Y"," ");
   define("SYSTOLICBP3Y"," ");
   define("SYSTOLICBP4Y"," ");
   define("SYSTOLICBP5Y"," ");
   define("DIASTOLICBP3M"," ");
   define("DIASTOLICBP9M"," ");
   define("DIASTOLICBP1Y"," ");
   define("DIASTOLICBP2Y"," ");
   define("DIASTOLICBP3Y"," ");
   define("DIASTOLICBP4Y"," ");
   define("DIASTOLICBP5Y"," ");
   define("PULSE3M"," ");
   define("PULSE9M"," ");
   define("PULSE1Y"," ");
   define("PULSE2Y"," ");
   define("PULSE3Y"," ");
   define("PULSE4Y"," ");
   define("PULSE5Y"," ");
   define("RESPIRATION3M"," ");
   define("RESPIRATION9M"," ");
   define("RESPIRATION1Y"," ");
   define("RESPIRATION2Y"," ");
   define("RESPIRATION3Y"," ");
   define("RESPIRATION4Y"," ");
   define("RESPIRATION5Y"," ");
   define("TEMP3M"," ");
   define("TEMP9M"," ");
   define("TEMP1Y"," ");
   define("TEMP2Y"," ");
   define("TEMP3Y"," ");
   define("TEMP4Y"," ");
   define("TEMP5Y"," ");
   define("MAC3M"," ");
   define("MAC9M"," ");
   define("MAC1Y"," ");
   define("MAC2Y"," ");
   define("MAC3Y"," ");
   define("MAC4Y"," ");
   define("MAC5Y"," ");
   define("TSF3M"," ");
   define("TSF9M"," ");
   define("TSF1Y"," ");
   define("TSF2Y"," ");
   define("TSF3Y"," ");
   define("TSF4Y"," ");
   define("TSF5Y"," ");
   define("PECTORALSF3M"," ");
   define("PECTORALSF9M"," ");
   define("PECTORALSF1Y"," ");
   define("PECTORALSF2Y"," ");
   define("PECTORALSF3Y"," ");
   define("PECTORALSF4Y"," ");
   define("PECTORALSF5Y"," ");
   define("SUBSCAPULASF3M"," ");
   define("SUBSCAPULASF9M"," ");
   define("SUBSCAPULASF1Y"," ");
   define("SUBSCAPULASF2Y"," ");
   define("SUBSCAPULASF3Y"," ");
   define("SUBSCAPULASF4Y"," ");
   define("SUBSCAPULASF5Y"," ");
   define("MIDAXILLASF3M"," ");
   define("MIDAXILLASF9M"," ");
   define("MIDAXILLASF1Y"," ");
   define("MIDAXILLASF2Y"," ");
   define("MIDAXILLASF3Y"," ");
   define("MIDAXILLASF4Y"," ");
   define("MIDAXILLASF5Y"," ");
   define("ABDOMENSF3M"," ");
   define("ABDOMENSF9M"," ");
   define("ABDOMENSF1Y"," ");
   define("ABDOMENSF2Y"," ");
   define("ABDOMENSF3Y"," ");
   define("ABDOMENSF4Y"," ");
   define("ABDOMENSF5Y"," ");
   define("SUPRAILIACSF3M"," ");
   define("SUPRAILIACSF9M"," ");
   define("SUPRAILIACSF1Y"," ");
   define("SUPRAILIACSF2Y"," ");
   define("SUPRAILIACSF3Y"," ");
   define("SUPRAILIACSF4Y"," ");
   define("SUPRAILIACSF5Y"," ");
   define("QUADRICEPSSF3M"," ");
   define("QUADRICEPSSF9M"," ");
   define("QUADRICEPSSF1Y"," ");
   define("QUADRICEPSSF2Y"," ");
   define("QUADRICEPSSF3Y"," ");
   define("QUADRICEPSSF4Y"," ");
   define("QUADRICEPSSF5Y"," ");
   define("WAISTCIRCUMFERENCE3M"," ");
   define("WAISTCIRCUMFERENCE9M"," ");
   define("WAISTCIRCUMFERENCE1Y"," ");
   define("WAISTCIRCUMFERENCE2Y"," ");
   define("WAISTCIRCUMFERENCE3Y"," ");
   define("WAISTCIRCUMFERENCE4Y"," ");
   define("WAISTCIRCUMFERENCE5Y"," ");
   define("HIPCIRCUMFERENCE3M"," ");
   define("HIPCIRCUMFERENCE9M"," ");
   define("HIPCIRCUMFERENCE1Y"," ");
   define("HIPCIRCUMFERENCE2Y"," ");
   define("HIPCIRCUMFERENCE3Y"," ");
   define("HIPCIRCUMFERENCE4Y"," ");
   define("HIPCIRCUMFERENCE5Y"," ");
   define("BODYFATPERCENTAGE3M"," ");
   define("BODYFATPERCENTAGE9M"," ");
   define("BODYFATPERCENTAGE1Y"," ");
   define("BODYFATPERCENTAGE2Y"," ");
   define("BODYFATPERCENTAGE3Y"," ");
   define("BODYFATPERCENTAGE4Y"," ");
   define("BODYFATPERCENTAGE5Y"," ");
   define("HBALC3M"," ");
   define("HBALC9M"," ");
   define("HBALC1Y"," ");
   define("HBALC2Y"," ");
   define("HBALC3Y"," ");
   define("HBALC4Y"," ");
   define("HBALC5Y"," ");
   define("BS3M"," ");
   define("BS9M"," ");
   define("BS1Y"," ");
   define("BS2Y"," ");
   define("BS3Y"," ");
   define("BS4Y"," ");
   define("BS5Y"," ");
   define("TG3M"," ");
   define("TG9M"," ");
   define("TG1Y"," ");
   define("TG2Y"," ");
   define("TG3Y"," ");
   define("TG4Y"," ");
   define("TG5Y"," ");
   define("TOTALCHOLESTEROL3M"," ");
   define("TOTALCHOLESTEROL9M"," ");
   define("TOTALCHOLESTEROL1Y"," ");
   define("TOTALCHOLESTEROL2Y"," ");
   define("TOTALCHOLESTEROL3Y"," ");
   define("TOTALCHOLESTEROL4Y"," ");
   define("TOTALCHOLESTEROL5Y"," ");
   define("HDL3M"," ");
   define("HDL9M"," ");
   define("HDL1Y"," ");
   define("HDL2Y"," ");
   define("HDL3Y"," ");
   define("HDL4Y"," ");
   define("HDL5Y"," ");
   define("LDL3M"," ");
   define("LDL9M"," ");
   define("LDL1Y"," ");
   define("LDL2Y"," ");
   define("LDL3Y"," ");
   define("LDL4Y"," ");
   define("LDL5Y"," ");
   define("TBG3M"," ");
   define("TBG9M"," ");
   define("TBG1Y"," ");
   define("TBG2Y"," ");
   define("TBG3Y"," ");
   define("TBG4Y"," ");
   define("TBG5Y"," ");
   define("URINERBC3M"," ");
   define("URINERBC9M"," ");
   define("URINERBC1Y"," ");
   define("URINERBC2Y"," ");
   define("URINERBC3Y"," ");
   define("URINERBC4Y"," ");
   define("URINERBC5Y"," ");
   define("URINEROTEIN3M"," ");
   define("URINEROTEIN9M"," ");
   define("URINEROTEIN1Y"," ");
   define("URINEROTEIN2Y"," ");
   define("URINEROTEIN3Y"," ");
   define("URINEROTEIN4Y"," ");
   define("URINEROTEIN5Y"," ");
   define("URINESG3M"," ");
   define("URINESG9M"," ");
   define("URINESG1Y"," ");
   define("URINESG2Y"," ");
   define("URINESG3Y"," ");
   define("URINESG4Y"," ");
   define("URINESG5Y"," ");
   define("URINEPH3M"," ");
   define("URINEPH9M"," ");
   define("URINEPH1Y"," ");
   define("URINEPH2Y"," ");
   define("URINEPH3Y"," ");
   define("URINEPH4Y"," ");
   define("URINEPH5Y"," ");
   define("URINECRYSTAL3M"," ");
   define("URINECRYSTAL9M"," ");
   define("URINECRYSTAL1Y"," ");
   define("URINECRYSTAL2Y"," ");
   define("URINECRYSTAL3Y"," ");
   define("URINECRYSTAL4Y"," ");
   define("URINECRYSTAL5Y"," ");
   define("URINECAST3M"," ");
   define("URINECAST9M"," ");
   define("URINECAST1Y"," ");
   define("URINECAST2Y"," ");
   define("URINECAST3Y"," ");
   define("URINECAST4Y"," ");
   define("URINECAST5Y"," ");
   define("CRP3M"," ");
   define("CRP9M"," ");
   define("CRP1Y"," ");
   define("CRP2Y"," ");
   define("CRP3Y"," ");
   define("CRP4Y"," ");
   define("CRP5Y"," ");
   define("ESR3M"," ");
   define("ESR9M"," ");
   define("ESR1Y"," ");
   define("ESR2Y"," ");
   define("ESR3Y"," ");
   define("ESR4Y"," ");
   define("ESR5Y"," ");
   define("ALBUMIN3M"," ");
   define("ALBUMIN9M"," ");
   define("ALBUMIN1Y"," ");
   define("ALBUMIN2Y"," ");
   define("ALBUMIN3Y"," ");
   define("ALBUMIN4Y"," ");
   define("ALBUMIN5Y"," ");
   define("PREALBUMIN3M"," ");
   define("PREALBUMIN9M"," ");
   define("PREALBUMIN1Y"," ");
   define("PREALBUMIN2Y"," ");
   define("PREALBUMIN3Y"," ");
   define("PREALBUMIN4Y"," ");
   define("PREALBUMIN5Y"," ");
   define("TOTALPROTEIN3M"," ");
   define("TOTALPROTEIN9M"," ");
   define("TOTALPROTEIN1Y"," ");
   define("TOTALPROTEIN2Y"," ");
   define("TOTALPROTEIN3Y"," ");
   define("TOTALPROTEIN4Y"," ");
   define("TOTALPROTEIN5Y"," ");
   define("DBILI3M"," ");
   define("DBILI9M"," ");
   define("DBILI1Y"," ");
   define("DBILI2Y"," ");
   define("DBILI3Y"," ");
   define("DBILI4Y"," ");
   define("DBILI5Y"," ");
   define("ALT3M"," ");
   define("ALT9M"," ");
   define("ALT1Y"," ");
   define("ALT2Y"," ");
   define("ALT3Y"," ");
   define("ALT4Y"," ");
   define("ALT5Y"," ");
   define("AST3M"," ");
   define("AST9M"," ");
   define("AST1Y"," ");
   define("AST2Y"," ");
   define("AST3Y"," ");
   define("AST4Y"," ");
   define("AST5Y"," ");
   define("ALKP3M"," P");
   define("ALKP9M"," P");
   define("ALKP1Y"," P");
   define("ALKP2Y"," P");
   define("ALKP3Y"," P");
   define("ALKP4Y"," P");
   define("ALKP5Y"," P");
   define("TSH3M"," ");
   define("TSH9M"," ");
   define("TSH1Y"," ");
   define("TSH2Y"," ");
   define("TSH3Y"," ");
   define("TSH4Y"," ");
   define("TSH5Y"," ");
   define("FREE3M"," ");
   define("FREE9M"," ");
   define("FREE1Y"," ");
   define("FREE2Y"," ");
   define("FREE3Y"," ");
   define("FREE4Y"," ");
   define("FREE5Y"," ");
   define("SERUMIRON3M"," ");
   define("SERUMIRON9M"," ");
   define("SERUMIRON1Y"," ");
   define("SERUMIRON2Y"," ");
   define("SERUMIRON3Y"," ");
   define("SERUMIRON4Y"," ");
   define("SERUMIRON5Y"," ");
   define("TIBC3M"," ");
   define("TIBC9M"," ");
   define("TIBC1Y"," ");
   define("TIBC2Y"," ");
   define("TIBC3Y"," ");
   define("TIBC4Y"," ");
   define("TIBC5Y"," ");
   define("FERRITIN3M"," ");
   define("FERRITIN9M"," ");
   define("FERRITIN1Y"," ");
   define("FERRITIN2Y"," ");
   define("FERRITIN3Y"," ");
   define("FERRITIN4Y"," ");
   define("FERRITIN5Y"," ");
   define("PTH3M"," ");
   define("PTH9M"," ");
   define("PTH1Y"," ");
   define("PTH2Y"," ");
   define("PTH3Y"," ");
   define("PTH4Y"," ");
   define("PTH5Y"," ");
   define("CA3M"," ");
   define("CA9M"," ");
   define("CA1Y"," ");
   define("CA2Y"," ");
   define("CA3Y"," ");
   define("CA4Y"," ");
   define("CA5Y"," ");
   define("P3M"," ");
   define("P9M"," ");
   define("P1Y"," ");
   define("P2Y"," ");
   define("P3Y"," ");
   define("P4Y"," ");
   define("P5Y"," ");
   define("MG3M"," ");
   define("MG9M"," ");
   define("MG1Y"," ");
   define("MG2Y"," ");
   define("MG3Y"," ");
   define("MG4Y"," ");
   define("MG5Y"," ");
   define("ZN3M"," ");
   define("ZN9M"," ");
   define("ZN1Y"," ");
   define("ZN2Y"," ");
   define("ZN3Y"," ");
   define("ZN4Y"," ");
   define("ZN5Y"," ");
   define("SELENIUM3M"," ");
   define("SELENIUM9M"," ");
   define("SELENIUM1Y"," ");
   define("SELENIUM2Y"," ");
   define("SELENIUM3Y"," ");
   define("SELENIUM4Y"," ");
   define("SELENIUM5Y"," ");
   define("COPPER3M"," ");
   define("COPPER9M"," ");
   define("COPPER1Y"," ");
   define("COPPER2Y"," ");
   define("COPPER3Y"," ");
   define("COPPER4Y"," ");
   define("COPPER5Y"," ");
   define("URICACID3M"," ");
   define("URICACID9M"," ");
   define("URICACID1Y"," ");
   define("URICACID2Y"," ");
   define("URICACID3Y"," ");
   define("URICACID4Y"," ");
   define("URICACID5Y"," ");
   define("VITAMINA3M"," ");
   define("VITAMINA9M"," ");
   define("VITAMINA1Y"," ");
   define("VITAMINA2Y"," ");
   define("VITAMINA3Y"," ");
   define("VITAMINA4Y"," ");
   define("VITAMINA5Y"," ");
   define("VITAMINB3M"," ");
   define("VITAMINB9M"," ");
   define("VITAMINB1Y"," ");
   define("VITAMINB2Y"," ");
   define("VITAMINB3Y"," ");
   define("VITAMINB4Y"," ");
   define("VITAMINB5Y"," ");
   define("VITAB3M"," ");
   define("VITAB9M"," ");
   define("VITAB1Y"," ");
   define("VITAB2Y"," ");
   define("VITAB3Y"," ");
   define("VITAB4Y"," ");
   define("VITAB5Y"," ");
   define("VITAC3M"," ");
   define("VITAC9M"," ");
   define("VITAC1Y"," ");
   define("VITAC2Y"," ");
   define("VITAC3Y"," ");
   define("VITAC4Y"," ");
   define("VITAC5Y"," ");
   define("VITAMD3M"," ");
   define("VITAMD9M"," ");
   define("VITAMD1Y"," ");
   define("VITAMD2Y"," ");
   define("VITAMD3Y"," ");
   define("VITAMD4Y"," ");
   define("VITAMD5Y"," ");
   define("FOLICACID3M"," ");
   define("FOLICACID9M"," ");
   define("FOLICACID1Y"," ");
   define("FOLICACID2Y"," ");
   define("FOLICACID3Y"," ");
   define("FOLICACID4Y"," ");
   define("FOLICACID5Y"," ");
   define("ANTIH3M"," ");
   define("ANTIH9M"," ");
   define("ANTIH1Y"," ");
   define("ANTIH2Y"," ");
   define("ANTIH3Y"," ");
   define("ANTIH4Y"," ");
   define("ANTIH5Y"," ");
   define("PROTEINC3M"," ");
   define("PROTEINC9M"," ");
   define("PROTEINC1Y"," ");
   define("PROTEINC2Y"," ");
   define("PROTEINC3Y"," ");
   define("PROTEINC4Y"," ");
   define("PROTEINC5Y"," ");
   define("PROTEINS3M"," ");
   define("PROTEINS9M"," ");
   define("PROTEINS1Y"," ");
   define("PROTEINS2Y"," ");
   define("PROTEINS3Y"," ");
   define("PROTEINS4Y"," ");
   define("PROTEINS5Y"," ");
   define("ANTITH3M"," ");
   define("ANTITH9M"," ");
   define("ANTITH1Y"," ");
   define("ANTITH2Y"," ");
   define("ANTITH3Y"," ");
   define("ANTITH4Y"," ");
   define("ANTITH5Y"," ");
   define("LH3M"," ");
   define("LH9M"," ");
   define("LH1Y"," ");
   define("LH2Y"," ");
   define("LH3Y"," ");
   define("LH4Y"," ");
   define("LH5Y"," ");
   define("FSH3M"," ");
   define("FSH9M"," ");
   define("FSH1Y"," ");
   define("FSH2Y"," ");
   define("FSH3Y"," ");
   define("FSH4Y"," ");
   define("FSH5Y"," ");
   define("GASTRITIS","Gastritis");
   define("GASTRITISS"," ");
   define("GASTRITISSIDE","Site");
   define("GASTRITISGR","grading");
   define("ULCERATION","Ulceration");
   define("ULCERATIONS"," ");
   define("ULCERATIONLOC","location");
   define("ABSTTOGLRA","Abnormal stroma to glands ratio");
   define("ABSTTOGLRATOO"," ");
   define("DISOFGL","Distortion of glands");
   define("DISOFGLABNORM"," ");
   define("METAPLASIA","Metaplasia");
   define("METAPLASIAINT"," ");
   define("METAPLASIAGRADING","grading");
   define("ABBLOOD","Abnormal Blood vessels");
   define("ABBLOODVAS"," ");
   define("MICTOOR","Microorganisms");
   define("MICTOORCO"," ");
   define("MICTOORCOL","colonization");
   define("NEOPLASIA","Neoplasia");
   define("NEOPLASIADY"," ");
   define("MENETRIER","Menetrier's disease");
   define("HEMORRHAGE","Hemorrhage");
   define("GRANULOMA","Granuloma");
   define("EROSIONS","Erosions");
   define("EPITHELIAL","Epithelial degeneration");
   define("PATHOLOGYRESDESC"," ");
   define("ANATOMICGA","Gastric outlet stenosis");
   define("ANATOMICGAWHEN","when");
   define("ANATOMICST","Stomal stenosis (R-Y bypass)");
   define("ANATOMICSTWHEN","when");
   define("ANATOMICOB","Stomal obstruction (LAGB)");
   define("ANATOMICOBWHEN","when");
   define("ANATOMICBA","Band erosion (LAGB)");
   define("ANATOMICBAWHEN","when");
   define("ANATOMICDIS","Band displacement (LAGB)");
   define("ANATOMICDISB"," ");
   define("ANATOMICDISWHEN","when");
   define("ANATOMILINEC","Staple line disruption (VBG)");
   define("ANATOMICLINEWHEN","when");
   define("ANATOMICER","Erosion of mesh band (VBG)");
   define("ANATOMICERWHEN","when");
   define("ANATOMICVE","Ventral incisional hernia");
   define("ANATOMICVEWHEN","when");
   define("ANATOMICHER","Internal hernia");
   define("ANATOMICHERWHEN","when");
   define("ANATOMICPOR","Port malfunction");
   define("ANATOMICPORWHEN","when");
   define("ANATOMICPORT","Port infection");
   define("ANATOMICPORTWHEN","when");
   define("BIOMECHANICGA","Gastric remnant distension (R-Y bypass)");
   define("BIOMECHANICGAWHEN","when");
   define("BIOMECHANICDI","Dilatation of gastric pouch");
   define("BIOMECHANICDIWHEN","when");
   define("BIOMECHANICDILA","Dilatation of gastrojejunal anastomosis (R-Y bypass)");
   define("BIOMECHANICDILAWHEN","when");
   define("BIOMECHANIESOC","Esophageal dilatation");
   define("BIOMECHANICESOWHEN","when");
   define("BIOMECHANICREF","Reflux");
   define("BIOMECHANICREFWHEN","when");
   define("BIOMECHANICREC","Recurrent vomiting (VBG)");
   define("BIOMECHANICRECWHEN","when");
   define("PHYSIOLOGICMA","Marginal ulceration");
   define("PHYSIOLOGICMAWHEN","when");
   define("PHYSIOLOGICDU","Dumping syndrome");
   define("PHYSIOLOGICDUWHEN","when");
   define("PHYSIOLOGICPOS","Postoperative hypoglycemia");
   define("PHYSIOLOGICPOSWHEN","when");
   define("PHYSIOLOGICNEP","Nephrolithiasis");
   define("PHYSIOLOGICNEPWHEN","when");
   define("PHYSIOLOGICRENAL","Renal failure");
   define("PHYSIOLOGICRENALW","when");
   define("PHYSIOLOGICCHO","Cholelithiasis");
   define("PHYSIOLOGICCHOWHEN","when");
   define("PHYSIOLOGICCHOL","Cholecystis");
   define("PHYSIOLOGICCHOLW","when");
   define("PHYSIOLOGICC","Cholangitis");
   define("PHYSIOLOGICCWHEN","when");
   define("PHYSIOLOGICCI","Cirrhosis");
   define("PHYSIOLOGICCIWHEN","when");
   define("MALNMI","Mineral deficiency");
   define("MALNMIWHEN","when");
   define("MALNVIT","Vitamin deficiency");
   define("MALNVITWHEN","when");
   define("MALNELE","Electrolyte imbalances (JIB)");
   define("MALNELEWHEN","when");
   define("MALNSH","Short bowel syndrome");
   define("MALNSHWHEN","when");
   define("MALNCHA","Change in bowel habits");
   define("MALNCHAWHEN","when");
   define("MALNHEM","Hemorrhoid");
   define("MALNHEMWHEN","when");
   define("MALNFIS","Fissure");
   define("MALNFISWHEN","when");
   define("FAILUREIN","Inadequate weight loss");
   define("FAILUREINWHEN","when");
   define("FAILUREWE","weight gain");
   define("FAILUREWEWHEN","when");
   define("FAILUREOTHER","Other");
   define("FAILUREDEC","Deceased");
   define("FAILUREDECDATE","Date");
   define("FAILUREDECCAUSE","Cause");
   define("COM_F_U"," ");
   define("FU_REQUIRE_FIELDS","");
   define("MSG_FU_SAVE","Saving Successfully");
   define("MSG_FU_DELETE","Delete Successfully");
?>

